const C=require('./lib/core');
const fields='id,first_name,last_name,phone,email,active,sms_opt_in,sms_opt_in_date,sms_opt_out_date,sms_consent_source,notes,created_at';
exports.handler=async event=>{try {if(!C.method(event,['GET','POST','PATCH'])) return C.fail(405,'Method not allowed.'); const profile=await C.requireRole(event,event.httpMethod!=='GET'); const type=event.queryStringParameters?.type; const id=event.queryStringParameters?.id; if(event.httpMethod==='GET') {
if(type==='members') { const [members,links,groups]=await Promise.all([C.table('members',`select=${fields}&order=first_name.asc&limit=500`),C.table('member_groups','select=member_id,group_id&limit=1000'),C.table('groups','select=id,name,description,archived&order=name.asc')]); return C.json(200,{members,links,groups}); }
if(type==='groups') {const [groups,links]=await Promise.all([C.table('groups','select=id,name,description,archived&order=name.asc'),C.table('member_groups','select=member_id,group_id&limit=1000')]);return C.json(200,{groups,links});}
if(type==='history') { const [messages,senders]=await Promise.all([C.table('messages',id&&C.uuid(id)?`id=eq.${id}&select=id,body,sender_user_id,audience_type,audience_description,selected_count,twilio_message_count,successful_count,failed_count,created_at&limit=1`:`select=id,body,sender_user_id,audience_type,audience_description,selected_count,twilio_message_count,successful_count,failed_count,created_at&order=created_at.desc&limit=50&offset=${Math.min(100,Math.max(0,Number(event.queryStringParameters?.page)||0))*50}`),C.table('admin_profiles','select=user_id,display_name&limit=100')]); const recipients=id&&C.uuid(id)?await C.table('message_recipients',`message_id=eq.${id}&select=id,member_id,phone,twilio_sid,status,error_code,error_message,created_at&limit=500`):[]; return C.json(200,{messages,senders,recipients}); }
if(type==='inbox') {if(profile.role==='viewer')return C.fail(403,'Access denied.');const inbound=await C.table('inbound_messages','select=id,twilio_sid,from_phone,to_phone,member_id,body,received_at,read&order=received_at.desc&limit=200');const members=await C.table('members','select=id,first_name,last_name,phone&limit=500');return C.json(200,{inbound,members});}
if(type==='conversation') {
  if(profile.role==='viewer') return C.fail(403,'Access denied.');
  const phone=C.inboundPhone(event.queryStringParameters?.phone);
  const [inbound,recipients]=await Promise.all([
    C.table('inbound_messages',`from_phone=eq.${encodeURIComponent(phone)}&select=id,body,received_at&order=received_at.desc&limit=200`),
    C.table('message_recipients',`phone=eq.${encodeURIComponent(phone)}&select=message_id,status,created_at&order=created_at.desc&limit=200`)
  ]);
  const ids=[...new Set(recipients.map(row=>row.message_id).filter(C.uuid))];
  const batches=[];
  for(let start=0;start<ids.length;start+=50) batches.push(ids.slice(start,start+50));
  const messages=(await Promise.all(batches.map(batch=>
    C.table('messages',`id=in.(${batch.join(',')})&select=id,body,created_at`)))).flat();
  const byId=new Map(messages.map(message=>[message.id,message]));
  const entries=[
    ...inbound.map(row=>({direction:'inbound',body:row.body,at:row.received_at})),
    ...recipients.flatMap(row=>{const message=byId.get(row.message_id);return message?[{direction:'outbound',body:message.body,status:row.status,at:row.created_at}]:[];})
  ].sort((a,b)=>new Date(a.at)-new Date(b.at));
  return C.json(200,{phone,entries});
}
if(type==='dashboard') {const [members,groups,messages,inbound]=await Promise.all([C.table('members','select=active,sms_opt_in,sms_opt_out_date&limit=500'),C.table('groups','select=id,archived&limit=100'),C.table('messages','select=id,created_at&order=created_at.desc&limit=500'),C.table('inbound_messages','select=id,read&limit=500')]);const month=new Date().toISOString().slice(0,7);return C.json(200,{active:members.filter(x=>x.active).length,subscribers:members.filter(x=>x.active&&x.sms_opt_in).length,optedOut:members.filter(x=>x.sms_opt_out_date).length,groups:groups.filter(x=>!x.archived).length,messagesThisMonth:messages.filter(x=>x.created_at.startsWith(month)).length,unread:inbound.filter(x=>!x.read).length});}
return C.fail(400,'Unknown data type.');}
const data=C.parse(event); if(type==='members') {if(!['admin','messaging_admin'].includes(profile.role)) return C.fail(403,'Access denied.'); if(!['POST','PATCH'].includes(event.httpMethod)) return C.fail(405,'Method not allowed.');if(event.httpMethod==='PATCH'&&!C.uuid(id)) return C.fail(400,'Invalid member.'); const first_name=String(data.first_name||'').trim(),last_name=String(data.last_name||'').trim(),email=String(data.email||'').trim(),notes=String(data.notes||'').trim();if(!first_name||first_name.length>100||last_name.length>100||email.length>255||notes.length>2000||typeof data.sms_opt_in!=='boolean'||typeof data.active!=='boolean'||!Array.isArray(data.group_ids)||!C.ids(data.group_ids))return C.fail(400,'Check member fields.');const number=C.phone(data.phone);if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return C.fail(400,'Enter a valid email.');const availableGroups=await C.table('groups','select=id,archived&limit=100');if(data.group_ids.some(groupId=>!availableGroups.some(group=>group.id===groupId&&!group.archived)))return C.fail(400,'Choose active groups.');const prior=event.httpMethod==='PATCH'?(await C.table('members',`id=eq.${id}&select=id,sms_opt_in,sms_opt_out_date`))[0]:null;if(event.httpMethod==='PATCH'&&!prior)return C.fail(404,'Member not found.');if(prior?.sms_opt_out_date&&data.sms_opt_in) return C.fail(400,'This member opted out. They must text START before resubscribing.');const opt=Boolean(data.sms_opt_in);const payload={first_name,last_name,phone:number,email:email||null,notes:notes||null,active:data.active!==false,sms_opt_in:opt,updated_at:new Date().toISOString()};if(opt&&!prior?.sms_opt_in){payload.sms_opt_in_date=new Date().toISOString();payload.sms_consent_source='leader_confirmed';}if(!opt&&prior?.sms_opt_in)payload.sms_opt_out_date=new Date().toISOString();const options={method:event.httpMethod,body:payload,prefer:'return=representation'};const result=await C.table('members',event.httpMethod==='PATCH'?`id=eq.${id}`:'',options);const member=result[0];await C.supa('/rest/v1/rpc/replace_member_groups',{method:'POST',body:{p_member_id:member.id,p_group_ids:data.group_ids}});return C.json(200,{member});}
if(type==='groups') {if(!['admin','messaging_admin'].includes(profile.role))return C.fail(403,'Access denied.');if(!['POST','PATCH'].includes(event.httpMethod))return C.fail(405,'Method not allowed.');if(event.httpMethod==='PATCH'&&!C.uuid(id))return C.fail(400,'Invalid group.');const name=String(data.name||'').trim(),description=String(data.description||'').trim();if(!name||name.length>100||description.length>500||typeof data.archived!=='boolean'||!C.ids(data.member_ids||[]))return C.fail(400,'Check group fields.');const availableMembers=await C.table('members','select=id&limit=500');if((data.member_ids||[]).some(memberId=>!availableMembers.some(member=>member.id===memberId)))return C.fail(400,'Choose existing members.');if(event.httpMethod==='PATCH'&&!(await C.table('groups',`id=eq.${id}&select=id&limit=1`))[0])return C.fail(404,'Group not found.');const payload={name,description:description||null,archived:Boolean(data.archived)};const result=await C.table('groups',event.httpMethod==='PATCH'?`id=eq.${id}`:'',{method:event.httpMethod,body:payload,prefer:'return=representation'});const group=result[0];await C.supa('/rest/v1/rpc/replace_group_members',{method:'POST',body:{p_group_id:group.id,p_member_ids:data.member_ids||[]}});return C.json(200,{group});}
if(type==='inbox'&&event.httpMethod==='PATCH'&&C.uuid(id)) {await C.table('inbound_messages',`id=eq.${id}`,{method:'PATCH',body:{read:Boolean(data.read)}});return C.json(200,{ok:true});}return C.fail(400,'Invalid request.');}catch(e){return C.handle(e);}};
