const { createHmac, timingSafeEqual } = require('node:crypto');
const json = (statusCode, data, extra = {}) => ({statusCode, headers: {'content-type':'application/json; charset=utf-8','cache-control':'no-store',...extra}, body: JSON.stringify(data)});
const fail = (status, error) => json(status, {error});
const parse = (event) => { try { const value=JSON.parse(event.body || '{}'); if (!value || typeof value !== 'object' || Array.isArray(value)) throw Error(); return value; } catch { throw Object.assign(new Error('Invalid JSON.'), {status:400}); } };
const header = (event,name) => Object.entries(event.headers || {}).find(([key])=>key.toLowerCase()===name)?.[1];
const originOK = event => { const origin=header(event,'origin'); if (!origin) return true; try { return new URL(origin).host===header(event,'host'); } catch { return false; } };
const method = (event, allowed) => allowed.includes(event.httpMethod) && (event.httpMethod === 'GET' || originOK(event));
const uuid = value => typeof value === 'string' && /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(value);
const ids = value => Array.isArray(value) && value.length <= 100 && value.every(uuid);
function phone(value) { const digits = String(value || '').replace(/\D/g,''); const local = digits.length === 11 && digits[0] === '1' ? digits.slice(1) : digits; if (!/^[2-9]\d{2}[2-9]\d{6}$/.test(local)) throw Object.assign(new Error('Enter a valid U.S. phone number.'),{status:400}); return `+1${local}`; }
function inboundPhone(value) { try { return phone(value); } catch { const number=String(value || '').trim(); if (/^\+[1-9]\d{1,14}$/.test(number)) return number; throw Object.assign(new Error('Invalid sender number.'),{status:400}); } }
function command(body, optOutType) { const t = String(optOutType || body || '').trim().toUpperCase(); if (['STOP','STOPALL','UNSUBSCRIBE','CANCEL','END','QUIT','REVOKE','OPTOUT'].includes(t)) return 'STOP'; if (['START','UNSTOP'].includes(t)) return 'START'; if (['HELP','INFO'].includes(t)) return 'HELP'; return null; }
function selectRecipients(members, groups, audience, groupIds = [], memberIds = []) { const set = new Set(), phones = new Set(), chosen = []; const skipped = {inactive:0,unsubscribed:0,invalid:0,duplicate:0}; for (const m of members) { const match = audience === 'all' || (audience === 'individual' && memberIds.includes(m.id)) || (audience === 'group' && groups.some(g => g.member_id === m.id && groupIds.includes(g.group_id))); if (!match || set.has(m.id)) continue; set.add(m.id); if (!m.active) { skipped.inactive++; continue; } if (!m.sms_opt_in) { skipped.unsubscribed++; continue; } let number; try { number = phone(m.phone); } catch { skipped.invalid++; continue; } if (phones.has(number)) { skipped.duplicate++; continue; } phones.add(number); chosen.push({...m,phone:number}); } return {chosen,skipped,selected:set.size}; }
function segments(body) {
  const extended = new Set([...'^{}\\[~]|€\f']);
  const otherBasic = new Set([...`£¥èéùìòÇØøÅåΔ_ΦΓΛΩΠΨΣΘΞÆæßÉÄÖÑÜ§¿äöñüà¡\n\r`]);
  const characters = [...body];
  const gsm = characters.every(c => extended.has(c) || otherBasic.has(c) ||
    (c.codePointAt(0) >= 32 && c.codePointAt(0) <= 126 && c !== '`'));
  const units = gsm ? characters.reduce((n, c) => n + (extended.has(c) ? 2 : 1), 0) : body.length;
  const size = gsm ? (units <= 160 ? 160 : 153) : (units <= 70 ? 70 : 67);
  return {encoding:gsm ? 'GSM-7' : 'Unicode', characters:characters.length, units,
    segments:Math.max(1, Math.ceil(units / size))};
}
const env = key => { const v=process.env[key]; if (!v) throw Object.assign(new Error('Server configuration is missing.'),{status:503}); return v; };
async function supa(path, {method='GET', body, token, prefer}={}) { const url = `${env('SUPABASE_URL').replace(/\/$/,'')}${path}`; const key=env('SUPABASE_SERVICE_ROLE_KEY'); const headers={apikey:key,'Content-Type':'application/json',...(prefer?{Prefer:prefer}:{})}; if (token) headers.Authorization=`Bearer ${token}`; else if (!key.startsWith('sb_secret_')) headers.Authorization=`Bearer ${key}`; const res = await fetch(url,{method,headers,body:body === undefined?undefined:JSON.stringify(body)}); const data = await res.json().catch(()=>null); if (!res.ok) { console.error('Database request failed',res.status,path.split('?')[0]); throw Object.assign(new Error(res.status === 409?'A record with this value already exists.':'Database request failed.'),{status:res.status===409?409:502}); } return data; }
const table = (name, query='', options={}) => supa(`/rest/v1/${name}${query ? `?${query}`:''}`,options);
const cookie = (event,name) => (header(event,'cookie') || '').split(';').map(x=>x.trim()).find(x=>x.startsWith(`${name}=`))?.slice(name.length+1);
const cookies = (access,refresh,maxAge=3600) => ({multiValueHeaders:{'Set-Cookie':[`ngc_access=${access}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=${maxAge}`,`ngc_refresh=${refresh}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=${refresh?2592000:0}`]}});
async function authUser(event) { const access=cookie(event,'ngc_access'); if (!access) throw Object.assign(new Error('Your session has expired. Please sign in again.'),{status:401}); const res=await fetch(`${env('SUPABASE_URL').replace(/\/$/,'')}/auth/v1/user`,{headers:{apikey:env('SUPABASE_ANON_KEY'),Authorization:`Bearer ${access}`}}); if (!res.ok) throw Object.assign(new Error('Your session has expired. Please sign in again.'),{status:401}); return res.json(); }
async function requireRole(event, write=false) { const user=await authUser(event); const rows=await table('admin_profiles',`user_id=eq.${encodeURIComponent(user.id)}&select=user_id,display_name,role,active`); const profile=rows[0]; if (!profile?.active || !['admin','messaging_admin','viewer'].includes(profile.role) || (write && profile.role==='viewer')) throw Object.assign(new Error('Access denied.'),{status:403}); return profile; }
function handle(error) { if (error.status && error.status < 500) return fail(error.status,error.message); console.error('Messaging function error',error.message); return fail(error.status || 500,error.status===503?'Server configuration is missing.':'Something went wrong. Please try again.'); }
const formBody = event => event.isBase64Encoded ? Buffer.from(event.body || '', 'base64').toString('utf8') : event.body || '';
function twilioValid(event) { const signature=header(event,'x-twilio-signature'); if (!signature) return false; const rawQuery=event.rawUrl ? new URL(event.rawUrl).search : event.rawQuery ? `?${event.rawQuery}` : event.queryStringParameters && Object.keys(event.queryStringParameters).length ? `?${new URLSearchParams(event.queryStringParameters)}` : ''; const url=`${env('SITE_URL').replace(/\/$/,'')}${event.path}${rawQuery}`; const params=new URLSearchParams(formBody(event)); const keys=[...new Set(params.keys())].sort(); const input=url+keys.map(k=>k+params.get(k)).join(''); const expected=createHmac('sha1',env('TWILIO_AUTH_TOKEN')).update(input).digest('base64'); const a=Buffer.from(expected),b=Buffer.from(signature); return a.length===b.length && timingSafeEqual(a,b); }
async function twilioSend(to,body,statusUrl) { const sid=env('TWILIO_ACCOUNT_SID'),token=env('TWILIO_AUTH_TOKEN'); const form=new URLSearchParams({To:to,Body:body}); if(statusUrl) form.set('StatusCallback',statusUrl); if (process.env.TWILIO_MESSAGING_SERVICE_SID) form.set('MessagingServiceSid',process.env.TWILIO_MESSAGING_SERVICE_SID); else form.set('From',env('TWILIO_PHONE_NUMBER')); const res=await fetch(`https://api.twilio.com/2010-04-01/Accounts/${sid}/Messages.json`,{method:'POST',headers:{Authorization:`Basic ${Buffer.from(`${sid}:${token}`).toString('base64')}`,'Content-Type':'application/x-www-form-urlencoded'},body:form,signal:AbortSignal.timeout(8000)}); const data=await res.json(); if (!res.ok) return {ok:false,error_code:String(data.code || ''),error_message:'Twilio rejected this message.'}; return {ok:true,sid:data.sid,status:['queued','sent','delivered'].includes(data.status)?data.status:'queued'}; }
module.exports={json,fail,parse,method,uuid,ids,phone,inboundPhone,command,selectRecipients,segments,env,supa,table,cookie,cookies,authUser,requireRole,handle,formBody,twilioValid,twilioSend};
